name: Nodejs project
on: 
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'npm'
      - name: npm install, build and test
        run: |
          npm install
      - name: Build and push the docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: maheshryali/nodejsnew
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        

